### ISSUE TITLE
Permission to place on nimgame.online

### ISSUE THREAD

**Issue by JohnAD** [dom96/snake#10]
With the MIT license, I don't *technically* have to ask. But I think it is more polite in this particular circumstance.

May I place your game on my https://nimgame.online website; including a link back to this repo?

**Comment by dom96** [comment]
@JohnAD thanks for asking, and absolutely, feel free. You can even link it directly from my website if you wish.

**Comment by dom96** [comment]
Nice website btw, I might have another game for you soon. Something a bit more serious and closed source, so maybe not the right place for it though :)
